@startuml
'https://plantuml.com/activity-diagram-beta

start

switch (Tastaturpuffer auslesen)
case ( <0 )
  :ungültige Eingabe;
  stop
case ( == 0)
  :Ergebnis = 0;
case (             zwischen 0;4)
  : A = Tastaturpuffer;
  : B = 0 ;
  : Ergebnis = 1;
  while (B <= A)
    :Ergebnis = Ergebnis * (B+1);
    :B = B + 1;
  endwhile(Fakultät berechnet)

case ( >4 )
  :ungültige Eingabe;
  stop;

endswitch

:Ergebnis auf Bildschirm Ausgeben;

stop

@enduml
