@startuml
'https://plantuml.com/activity-diagram-beta
(*) --> "**Variablen Dekleration**
          COUNTER = 1
          ERG = 1
          ERG2 = 2
          ERGH = 1
          FAKLT = 0
          "

-->"Tastaturpuffer auslesen
    & in DEC auf FAKLT speichern"

if "FAKLT = 0" then
--> [true]"Ausgabe ERG"
-left->(*)
else
    -->if "FAKLT = 1" then
    -> [true]"Ausgabe ERG"
    else
        if "FAKLT > 4" then
        -->[true](*)
        else
        ->[false]"LOOP"
        Endif
        Endif
        Endif

-->if "FAKLT = COUNTER" then
    -->[true]"Ausgabe ERG"
    else
    -->[false]"LOOP2"
    Endif

-->"ERG = ERG + ERGH"
-->"ERG2 = ERG2 - 1"

if "ERG2 = EINS" then
    -->[true]"LOOP3"
    -->"ERGH = ERG"
    -->"COUNTER = COUNTER + 1"
    -->"ERG2 = COUNTER + 1"
    -->"LOOP"
    else
    -->[false]"LOOP2"
    Endif








@enduml
